model: groq:llama-3.3-70b-versatile
clients:
- type: openai
- type: gemini
  api_key: ${GEMINI_API_KEY}
- type: openai-compatible
  name: groq
  api_base: https://api.groq.com/openai/v1
  api_key: ${GROQ_API_KEY}
  models:
    - name: llama-3.3-70b-versatile
      max_input_tokens: 131072
    - name: llama-3.1-8b-instant
      max_input_tokens: 131072
    - name: meta-llama/llama-4-maverick-17b-128e-instruct
      max_input_tokens: 131072
- type: openai-compatible
  name: openrouter
  api_base: https://openrouter.ai/api/v1
  api_key: ${OPEN_ROUTER_API_KEY}

document_loaders:
  pdf: 'pdftotext $1 -'
  docx: 'pandoc --to plain $1'

# Custom Gruvbox theme
highlight: true
theme: dark

roles_dir: ~/projects/dotfiles/aichat/roles

